### AgileXRMVersion 8.0.25007.20500
Param(
	[string]$apServiceAccountDomain ="INTERNAL",
	[string]$apServiceAccountUser ="apservice",
	$apServiceAccountPassword=$null,
	[string]$regionNumber="4",
	[string]$poolNumber="00",
	[string]$redisAccessKey = "",
	[string]$azureServiceBusConnectionString="",
	[string]$defaultGateway = "10.0.0.1",
	[string]$sqlServer="",
	[string]$sqlServerPort="1433",
	[string]$appUrlSeparator=".",
	[string]$domainUrl="agilexrmonline.com",
	[string]$mainHostName="pool",
	[string]$portalPort="443",
	[string]$azureAdRealm = "https://axrm.agilexrmonline.com",
	[string]$deploymentMode ="MT",
	[string]$deploymentType ="Cloud",
	[string]$localUsersPassword ="Default@1", 
	[string]$waadWcfAppId = "19e4137f-55ae-4dbf-9fbc-e386bbf36304",
	[string]$waadWcfAppIdUri = "https://ws.agilexrmonline.com:13487/AgilePointServer",
	[string]$waadApplicationId = "81c01359-21c1-467f-a3a8-52f5d6721fa0",
	[string]$waadApplicationIdPassword = $null,
	[string]$envisionAppId = "583a4e00-bcf2-4fbb-b346-6c90c376f160",
	[string]$singleTenantCrmOrgUniqueId ="ORGYYYYY" ,
	[string]$singleTenantCrmOrgFullUrl ="https://myorgyyy.crm4.dynamics.com",
	[string]$certificateSubjectName= "CN=agilexrmonline.com",
	[string]$singleTenantAdminUser ="apservice",
	[string]$anonymousUser,
	[string]$customStorageAzureConnString,
	[string]$azureStorageConnString,
	[string]$azureStorageTableName="AgileXRMGlobalOndemandStorage",
	$poolNotificationMailbox=$null,
	[string]$senderMailBox="notification@agilexrmonline.com",
	[string]$mailServer="smtp.office365.com:587:ssl",
	[string]$smtpService,
	[string]$tenantId = "b77e219c-0e95-404c-b671-4e48f654b3a4",
	[bool]$isScaleSet = $true,
	[string]$scaleSetName = "axrm498vmss",
	[string]$primaryNicName ="scaleSetLBNIC",
	[string]$apiNicName ="scaleSetLBNIC2",
	[string]$publicNicName ="scaleSetLBNIC3",
	[string]$portalNicName ="scaleSetLBNIC4",	
	[string]$resourceGroupName ="AgileXRMOnline",
	$svcPrincipalAppId=$null,
	$svcPrincipalSecretKey=$null,
	$autoRestart=$true,
	$singleApDB = "SingleAPDB",
	$masterPortalDB = "MasterPortalDB",
	$singlePortalDB = "SinglePortalDB",
	[string]$dbUserName="apservice",
	[string]$dbUserPassword="",
	[bool]$isSqlAzure = $false,
	[bool]$customizeNxPortal = $false,
	[string]$sqlServerAliasName = "SQL400"
)
$now = Get-Date -Format "yyyyMMddHHmmss"
$transcriptFileName = [string]::Format("PSWStartVM_{0}.log",$now)
$transcriptFilePath = Join-Path "C:\Temp" $transcriptFileName
Start-Transcript -Path $transcriptFilePath

Stop-Transcript
